import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CarBikes360</title>
        <meta name="description"content="Generated by create next app" />
        <link rel="icon" href="/logo2.jpg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.carbike360.com/">CarBikes360</a>
        </h1>

        <p className={styles.description}>
        
        </p>
        <div className={styles.grid}>
        <h2>Available Cars &rarr; </h2>

          <a href='' className='styles.card'>
          
          <div className={styles.card}>
            <div className={styles}>
              <Image className={styles.image} src="/345.jpg" alt="pic1" width="300px" height="200px"/>
              
            </div>
            <div>
            <Image className={styles.image} src="/656.jpg" width="300px" height="200px"/>
            
            </div>
            <div>
            <Image className={styles.image} src="/558.jpg" width="300px" height="200px"/>
           
            </div>
            <div>
            <Image className={styles.image} src="/788.jpg" width="300px" height="200px"/>
            
              
            </div>
          </div>
          </a>
         
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://www.carbike360.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{''}
          <span className={styles.logo}>
          <Image src="/car.jpg " alt="logo" width={72} height={16} />

          </span>
        </a>
      </footer>
    </div>
  )
}