import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import {Button, CardGroup, Card,} from 'react-bootstrap';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CarBikes360</title>
        <meta name="description"content="Generated by create next app" />
        <link rel="icon" href="/logo2.jpg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.carbike360.com/">CarBike360</a>
        </h1>

        <p className={styles.description}>
        <b>Details About The Cars</b>
    
          <code className={styles.code}></code>
        </p>
        <div className={styles.grid}>
        <h2>Available Cars &rarr; </h2>
         <a href='' className='styles.card'>
          <div className={styles.card}>
            <div className={styles}>
              <Image className={styles.image} src="/1111.jpg" alt="pic1" width="300px" height="200px"/>
              <h4>Honda City </h4>
              <h4>Rs 10.52 lakhs</h4>
              <h4><a href="/Cars/home2">View Details</a></h4>
            </div>
            <div>
            <Image className={styles.image} src="/5.jpg" width="300px" height="200px"/>
            <h4>Hyundai Venue</h4>
            <h4> Rs 7.53 lakhs</h4>
            <h4>
                <button type="button">View Details</button>
              </h4>
            </div>
            <div>
            <Image className={styles.image} src="/6.jpg" width="300px" height="200px"/>
            <h4>TATA Nexon</h4>
            <h4> Rs 7.89 lakhs</h4>
            <h4>
                <button type="button">View Details</button>
              </h4>
            </div>
            <div>
            <Image className={styles.image} src="/8.jpg" width="300px" height="200px"/>
            <h4>Renault Kiger</h4>
            <h4> Rs 6.18 lakhs</h4>
            <h4>
                <button type="button">View Details</button>
              </h4>
            </div>
          </div>
        </a>
         
        </div>
      </main>
     
    <CardGroup>
      <Card>
        <Card.Img variant="top" src="/99.jpg" width="250" height="250" />
        <Card.Body>
          <Card.Title>Card title</Card.Title>
          <Card.Text>
            This Car is Amazing.
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
      <Card>
      <Card.Img variant="top" src="/1002.jpg" width="250" height="250" />

        <Card.Body>
          <Card.Title>Card title</Card.Title>
          <Card.Text>
            This Car is Amazing.
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
      <Card>
      <Card.Img variant="top" src="/22.jpg" width="250" height="250" />

        <Card.Body>
          <Card.Title>Card title</Card.Title>
          <Card.Text>
            This Car is Amazing.
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
    </CardGroup>
      <footer className={styles.footer}>
        <a
          href="https://www.carbike360.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{''}
          <span className={styles.logo}>
            <Image src="/car.jpg " alt="logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}